[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Sequences protocols", "openItem": "False", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "BLAST", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtChemBLAST",   "text": "default"},
            {"tag": "protocol", "value": "ProtChemNCBIDownload",   "text": "default"},
            {"tag": "protocol", "value": "ProtChemBLASTDatabase",   "text": "default"}
        ]}
	]}
    ]
